---
- name: Configure Apache servers
  hosts: apache
  become: yes

  vars:
    html_source_path: "/var/lib/jenkins/workspace/terra-an-jen/html/"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy website files from HTML repo
      copy:
        src: "{{ html_source_path }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'


- name: Configure Nginx servers
  hosts: nginx
  become: yes

  vars:
    html_source_path: "/var/lib/jenkins/workspace/terra-an-jen/html/"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy website files from HTML repo
      copy:
        src: "{{ html_source_path }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
